### ISSUE TITLE
Possível integração com o Divi Builder

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/give-free-form#1]
Seria interessante que o Divi Builder apresentasse algumas opções do Free-Form nas edições de páginas:

* Poder alterar opções de cor, tamanho e espaçamento diretamente pelo Divi Builder;
* Fazer as opções selecionadas serem salvas no metadata do formulário;

É necessário testar se essa implementação seria viável, segue link com referência para extensão do Divi Builder: [https://www.elegantthemes.com/documentation/developers/how-to-create-a-divi-builder-module/](url)

**Comment by brunoferreiralkn** [comment]
O Give e o Divi não fornecem uma documentação necessária para podermos fazer essa integração de forma saudável e correta.
Se formos ter que debugar o código fonte dos dois elementos, vai ser muito desgastante.
Outro ponto é: vamos ficar a mercê de alterações que eles podem fazer no código deles, e então vamos ter que estudar ele novamente para adaptar nosso código.
