### ISSUE TITLE
Ajuste na mensagem Doação segura via Link

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/give-free-form#12]
A mensagem **'Doação segura via Link'** está causando confusão para alguns doadores. A mensagem parece com outra forma de doação e não remete a empresa Link Nacional, a sugestão seria mudar essa mensagem para ficar mais claro que o link **não é outra forma de doação.**

**Comment by souzadavi** [comment]
@emanuellopess fiz um commit no branch dev com um pequena alteração de estilo e redução. Tem alguma outra sugestão?

**Comment by emanuellopess** [comment]
@souzadavi Eu sugiro mudar a mensagem. "Doação segura via Link" ainda parece uma outra etapa de doação e pode confundir quem está doando. Podíamos mudar pra algo que remete a empresa Link Nacional ou colocar uma mensagem que não faça referência a doação.

**Comment by souzadavi** [comment]
@emanuellopess altere o texto para "Plataforma de doação online" pode ser?

**Comment by emanuellopess** [comment]
@souzadavi Sim! Isso deve resolver, irei abrir um pull request com a alteração, obrigado.
