### ISSUE TITLE
Ajustes nos atributos de layout

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/give-free-form#5]
* Separar tamanho da fonte dos níveis de doação do tamanho dos botões de selecionar métodos de pagamento;
* Separar tamanho de largura e altura dos botões de selecionar níveis de doação dos botões de selecionar métodos de pagamento;
* Adicionar opção de tamanho da fonte dos botões de níveis de doação e dos métodos de pagamento no mobile (responsividade);
* Ajustar usabilidade atualmente os campos onde ficam as alterações ficam bem obscuros dentro do submenu dos formulários;
* Adicionar campo para implementar CSS;
* Ajustar campos de tamanho para definir em texto especificando o tamanho e a forma de medida: 15px, 1em, 0.8rem, 2vw;

**Comment by kaueadelchi** [comment]
Na opção de cartão de débito, o botão de doar não fica com a cor nem a borda selecionada
![image](https://user-images.githubusercontent.com/31448688/125498895-e6af781f-609f-489f-9978-3627d033baee.png)
Nas opções de doar com pix paghiper, boleto bancário paghiper e de cartão de débito, o total da doação está a baixo do botão de doação.
![image](https://user-images.githubusercontent.com/31448688/125499245-fbd934a4-bb78-45f1-b3a3-d2509e06f2e6.png)
Nas opções de doar com visa checkout e googplay, o botão poderia ficar centralizado
![image](https://user-images.githubusercontent.com/31448688/125499832-86d23604-ec37-4566-ba95-6967af56ae7b.png)
![image](https://user-images.githubusercontent.com/31448688/125499877-ab594e29-9939-4349-8f0c-e8cc5495f57f.png)

**Comment by emanuellopess** [comment]
- [x] Adicionar campo CSS nas configurações;
- [x] Ajustar campos de tamanho para definir em texto especificando o tamanho e a forma de medida: 15px, 1em, 0.8rem, 2vw;
- [x] Adição de compatibilidade do 3DS com o give-free-form;
- [x] Adição de exemplos de implementações CSS no readme.md

**Comment by emanuellopess** [comment]
Feito no pull request #4
